export const contacts = [
  {
    id: 1,
    name: "Анна",
    surname: "Петрова",
    phone: "+7 912 345-67-89",
    email: "anna.petrova@example.com",
    notes: "Коллега с прошлой работы",
  },
  {
    id: 2,
    name: "Максим",
    surname: "Иванов",
    phone: "+7 923 456-78-90",
    email: "maxim.ivanov@example.com",
    notes: "Познакомились на конференции",
  },
  {
    id: 3,
    name: "Екатерина",
    surname: "Смирнова",
    phone: "+7 901 234-56-78",
    email: "ekaterina.smirnova@example.com",
    notes: "Подруга",
  },
  {
    id: 4,
    name: "Дмитрий",
    surname: "Козлов",
    phone: "+7 905 678-12-34",
    email: "dmitry.kozlov@example.com",
    notes: "Рабочие вопросы",
  },
  {
    id: 5,
    name: "Мария",
    surname: "Волкова",
    phone: "+7 916 789-23-45",
    email: "maria.volkova@example.com",
    notes: "Соседка",
  },
  {
    id: 6,
    name: "Алексей",
    surname: "Морозов",
    phone: "+7 999 123-45-67",
    email: "alexey.morozov@example.com",
    notes: "Помогает с ремонтом",
  },
  {
    id: 7,
    name: "Ольга",
    surname: "Соколова",
    phone: "+7 927 345-12-89",
    email: "olga.sokolova@example.com",
    notes: "Одногруппница",
  },
  {
    id: 8,
    name: "Артём",
    surname: "Лебедев",
    phone: "+7 903 567-89-01",
    email: "artem.lebedev@example.com",
    notes: "",
  },
  {
    id: 9,
    name: "Виктория",
    surname: "Новикова",
    phone: "+7 915 234-78-56",
    email: "victoria.novikova@example.com",
    notes: "Клиент",
  },
  {
    id: 10,
    name: "Илья",
    surname: "Фёдоров",
    phone: "+7 980 456-23-17",
    email: "ilya.fedorov@example.com",
    notes: "Друг детства",
  },
];
